# Generated by Django 2.2.5 on 2019-09-16 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='postal_coe',
            new_name='postal_code',
        ),
    ]
