# Generated by Django 2.2.5 on 2019-09-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_auto_20190916_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='adress_line_1',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
