# Generated by Django 2.2.5 on 2019-09-29 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketingprefence',
            old_name='mailchimp_msj',
            new_name='mailchimp_msg',
        ),
    ]
