# Generated by Django 2.2.5 on 2019-10-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_auto_20190929_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingprefence',
            name='mailchimp_subscribed',
            field=models.NullBooleanField(),
        ),
    ]
