# Generated by Django 2.2.5 on 2019-10-01 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_marketingprefence_mailchimp_subscribed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketingprefence',
            old_name='update',
            new_name='updated',
        ),
    ]
