# Generated by Django 2.2.5 on 2019-10-11 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
