# Generated by Django 2.2.5 on 2019-10-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_productpurchase_productpurchasemanager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpurchase',
            name='user',
        ),
        migrations.AddField(
            model_name='productpurchase',
            name='order_id',
            field=models.CharField(default='abc@gmail.com', max_length=120),
            preserve_default=False,
        ),
    ]
