# Generated by Django 2.2.5 on 2019-10-17 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_delete_productpurchasemanager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productpurchase',
            old_name='retunded',
            new_name='refunded',
        ),
    ]
