# Generated by Django 2.2.5 on 2019-09-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20190909_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='activse',
            field=models.BooleanField(default=True),
        ),
    ]
