# Generated by Django 2.2.5 on 2019-09-10 15:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_activse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='activse',
        ),
        migrations.AddField(
            model_name='product',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
