# Generated by Django 2.2.5 on 2019-10-18 09:03

import django.core.files.storage
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\Liduma\\Desktop\\Django\\ecommerce\\static\\protected_media'), upload_to=products.models.upload_product_file_loc),
        ),
    ]
